"""initial schema

Revision ID: f6e0d4715ba0
Revises: 
Create Date: 2026-05-05 15:36:02.920856
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6e0d4715ba0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('provider_pubkey', sa.String(length=66), nullable=True),
    sa.Column('provider_lightning_address', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('price_sats', sa.BigInteger(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('endpoint_url', sa.String(length=512), nullable=True),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    op.create_table('wallets',
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('balance_msats', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_owner_id'), 'wallets', ['owner_id'], unique=True)
    op.create_table('invoices',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('payment_request', sa.Text(), nullable=False),
    sa.Column('payment_hash', sa.String(length=64), nullable=False),
    sa.Column('preimage', sa.String(length=64), nullable=True),
    sa.Column('amount_msats', sa.BigInteger(), nullable=False),
    sa.Column('amount_paid_msats', sa.BigInteger(), nullable=False),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.Column('expiry_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SETTLED', 'CANCELLED', 'EXPIRED', name='invoicestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_payment_hash'), 'invoices', ['payment_hash'], unique=True)
    op.create_index(op.f('ix_invoices_wallet_id'), 'invoices', ['wallet_id'], unique=False)
    op.create_table('payments',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('payment_request', sa.Text(), nullable=False),
    sa.Column('payment_hash', sa.String(length=64), nullable=False),
    sa.Column('preimage', sa.String(length=64), nullable=True),
    sa.Column('amount_msats', sa.BigInteger(), nullable=False),
    sa.Column('fee_msats', sa.BigInteger(), nullable=False),
    sa.Column('platform_fee_msats', sa.BigInteger(), nullable=False),
    sa.Column('destination_pubkey', sa.String(length=66), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_FLIGHT', 'SUCCEEDED', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('route_hints_json', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_hash'), 'payments', ['payment_hash'], unique=False)
    op.create_index(op.f('ix_payments_wallet_id'), 'payments', ['wallet_id'], unique=False)
    op.create_table('skill_executions',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('consumer_pubkey', sa.String(length=66), nullable=True),
    sa.Column('consumer_name', sa.String(length=255), nullable=True),
    sa.Column('payment_hash', sa.String(length=64), nullable=True),
    sa.Column('payment_preimage', sa.String(length=64), nullable=True),
    sa.Column('amount_sats', sa.BigInteger(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAYMENT_RECEIVED', 'EXECUTING', 'COMPLETED', 'FAILED', 'REFUNDED', name='executionstatus'), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_executions_payment_hash'), 'skill_executions', ['payment_hash'], unique=False)
    op.create_index(op.f('ix_skill_executions_skill_id'), 'skill_executions', ['skill_id'], unique=False)
    op.create_table('ratings',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('rater_name', sa.String(length=255), nullable=True),
    sa.Column('rater_pubkey', sa.String(length=66), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('payment_preimage', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='valid_score_range'),
    sa.ForeignKeyConstraint(['execution_id'], ['skill_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_execution_id'), 'ratings', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_execution_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_skill_executions_skill_id'), table_name='skill_executions')
    op.drop_index(op.f('ix_skill_executions_payment_hash'), table_name='skill_executions')
    op.drop_table('skill_executions')
    op.drop_index(op.f('ix_payments_wallet_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_hash'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoices_wallet_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payment_hash'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_wallets_owner_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
