"""drop dead consumer_pubkey column

Revision ID: fad118a12739
Revises: c4d5e6f7a8b9
Create Date: 2026-06-17 22:35:06.146695
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad118a12739'
down_revision: Union[str, None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_executions', 'consumer_pubkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_executions', sa.Column('consumer_pubkey', sa.VARCHAR(length=66), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
